### PR TITLE
Write output to a temp file and rename it afterwards.

### LINKED ISSUE #20: Same filename for input and output doesn't work
Split away form #19. We should probably open the output file for writing first and truncate it only after we have the output JPEG ready.

### PR DESCRIPTION
**Pull request by robryk**
Fixes #20

### CODE REVIEW

**Comment by robryk** [comment]
PTAL

File: guetzli/guetzli.cc [hunk 1]
```diff
@@ -196,12 +196,6 @@ int main(int argc, char** argv) {
     return 1;
   }
```
Comment (szabadka) [inline guetzli/guetzli.cc]: Maybe close fin here?

Comment (robryk) [inline guetzli/guetzli.cc]: Done.
